#!/usr/bin/python3
"""
Factorize as many numbers as possible into
a product of two smaller prime numbers.

Functions:
    factorize()

Usage: ./rsa <file>
    Where <file> is a file containing one natural number to factor.
Output format: n=p*q
    p and q are always prime numbers.
"""

import sys
import ctypes


def factorize():
    """
    Factorizes as many numbers as possible into
    a product of two smaller prime numbers and print them.
    """

    c_factors = ctypes.CDLL("./lib_factors.so")
    c_factors.find_divisor.argtypes = [ctypes.c_long]
    with open(sys.argv[1]) as f:
        line = f.readline()
        while line != '':
            num = int(line)
            c_factors.find_divisor(num)
            line = f.readline()


if __name__ == "__main__":
    factorize()
